In [1]:
# Importing the Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset,drop_first=True)

In [5]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [6]:
dependent = dataset[['charges']]

In [7]:
from sklearn.ensemble import AdaBoostRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import r2_score

# Sample hyperparameter grid
param_grid = {
    'n_estimators': [50, 100, 150],
    'learning_rate': [0.01, 0.1, 1.0]
}

# Create GridSearchCV object
grid = GridSearchCV(
    AdaBoostRegressor(),
    param_grid,
    refit=True,
    verbose=3,
    n_jobs=-1
)

# Fit the model using the entire dataset
grid.fit(independent, dependent)

Fitting 5 folds for each of 9 candidates, totalling 45 fits

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

GridSearchCV(estimator=AdaBoostRegressor(), n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.1, 1.0],
                         'n_estimators': [50, 100, 150]},
             verbose=3)

In [8]:
# print best parameter after tuning
# print (grid.best_params_)
re = grid.cv_results_

from sklearn.metrics import r2_score

# Fit the model
grid.fit(independent, dependent)

# Predict on same data
y_pred = grid.predict(independent)

# Compute R²
r_score = r2_score(dependent, y_pred)
print("The R_score value for best parameter {}:".format(grid.best_params_), r_score)

Fitting 5 folds for each of 9 candidates, totalling 45 fits
The R_score value for best parameter {'learning_rate': 0.01, 'n_estimators': 50}: 0.8611483412115776

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

In [9]:
table = pd.DataFrame.from_dict(re)

In [10]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_learning_rate,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.168183,0.004959,0.013445,0.003593,0.01,50,"{'learning_rate': 0.01, 'n_estimators': 50}",0.873370,0.794625,0.880217,0.830766,0.864451,0.848686,0.031924,1
1,0.320932,0.015999,0.021556,0.002421,0.01,100,"{'learning_rate': 0.01, 'n_estimators': 100}",0.870882,0.797228,0.877213,0.831125,0.864085,0.848106,0.029994,2
2,0.458934,0.014735,0.026117,0.001094,0.01,150,"{'learning_rate': 0.01, 'n_estimators': 150}",0.866389,0.795876,0.872629,0.829875,0.862227,0.845399,0.028840,3
3,0.178842,0.012598,0.011826,0.001332,0.1,50,"{'learning_rate': 0.1, 'n_estimators': 50}",0.846268,0.790112,0.846943,0.814723,0.844155,0.828440,0.022647,5
4,0.226080,0.018546,0.012929,0.003850,0.1,100,"{'learning_rate': 0.1, 'n_estimators': 100}",0.839259,0.790609,0.842726,0.811809,0.836369,0.824154,0.020000,6
5,0.213318,0.011960,0.008719,0.002261,0.1,150,"{'learning_rate': 0.1, 'n_estimators': 150}",0.844669,0.783500,0.838950,0.815466,0.838119,0.824141,0.022641,7
6,0.031172,0.006416,0.006113,0.001467,1.0,50,"{'learning_rate': 1.0, 'n_estimators': 50}",0.830016,0.776081,0.832005,0.817762,0.832436,0.817660,0.021474,9
7,0.031273,0.009593,0.006316,0.001032,1.0,100,"{'learning_rate': 1.0, 'n_estimators': 100}",0.844182,0.789938,0.842571,0.791327,0.836144,0.820832,0.024808,8
8,0.029272,0.004572,0.005106,0.000804,1.0,150,"{'learning_rate': 1.0, 'n_estimators': 150}",0.843342,0.794926,0.854149,0.816319,0.846135,0.830974,0.022064,4

In [11]:
age_input=float(input("Age: "))
bmi_input=float(input("BMI: "))
children_input=float(input("Children: "))
sex_male_input=int(input("Sex Male 0 or 1: "))
smoker_yes_input=int(input("Smoker Yes 0 or 1: "))

Age: 43
BMI: 32
Children: 2
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [12]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[33209.95965686]